js_library(
    name = 'sagas',
    srcs = [
        'index.js',
    ],
    deps = [
        '//third_party/js:redux-saga',
    ],
    visibility = [
        '//vault/admin_app/frontend/app/',
    ],
)
